### ISSUE TITLE
User Story #19: Export Cart

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#19]
EPIC: **Export/Import**

As a **site user**, I want to **export the items in the cart**, so that I can **easily create a list of items to order**.

**Acceptance Criteria:**
1. When clicking export, the items are saved into a downloadable file.
2. The cart is cleared after exporting.

**Tasks:**
- [ ] Implement functionality to save all stock items with their information to a file
- [ ] Download the file
- [ ] Clear the cart
