### ISSUE TITLE
User Story #20: Scan QR Code

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#20]
EPIC: **Export/Import**

As a **site user**, I want to **update stock items by scanning a QR code**, so that I can **simplify the process of adding and removing items to/from my inventory**.

**Acceptance Criteria:**
1. A QR code can be scanned with the phone, there is a different code for each item.
2. It has to be ensured that the user is logged in.
3. The code links to a page where a stock item can be added,
4. On this page, the stock quantity can be changed.
5. On this page, the stock item can be added to the cart.

**Tasks:**
- [ ] Create QR code for stock item
- [ ] Ensure user is logged in when scanning the code
- [ ] Create detail page for stock item
- [ ] Allow changing the quantity of the scanned item
- [ ] Allow adding the scanned item to the cart
