### ISSUE TITLE
Dev Task #1: Set up project

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#22]
**Description:**
Set the project up and install the necessary libraries.

**Tasks:**
- [ ] Install Django
- [ ] Set up local IDE
- [ ] Link to Cloudinary
- [ ] Link to Database
