### ISSUE TITLE
Dev Task #3: Add Template

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#24]
**Description:**
Add a header and footer template with styling.

**Tasks:**
- [ ] Add the header template
- [ ] Style the header template
- [ ] Add the footer template
- [ ] Style the footer template
