### ISSUE TITLE
User Story #3: Manage roles

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#3]
EPIC: **User Authentication**

As a **site owner**, I want to **manage user roles**, so that I can **choose who can access sensitive information**.

**Acceptance Criteria:**
1. Only the site owner has access to the role management.
2. Employee role can be assigned to users.
3. Employee roles don´t have access to stock item prices.

**Tasks:**
- [ ] Add role management page
- [ ] Implement assignment of roles
- [ ] Hide prices for employees

**Comment by Julia-Wagner** [comment]
added role-based restrictions to delete categories and edit/delete closed delivery notes instead
