### ISSUE TITLE
Dev Task #4: Add a search bar

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#31]
**Description:**
Add a search bar for stock items.

**Tasks:**
- [ ] add the search bar
- [ ] query stock items
- [ ] show the found items in a table
- [ ] add a detail page for stock items
