### ISSUE TITLE
User Story #4: Create Categories

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#4]
EPIC: **Stock Items**

As a **site user**, I want to **create and view categories**, so that I can **organize my inventory**.

**Acceptance Criteria:**
1. A name, optional parent category and image can be added to a category.
2. Categories are displayed as a grid with the image and name.
3. Breadcrumbs are added for categories and subcategories.
4. Categories are clickable opening either the subcategory or the items overview.

**Tasks:**
- [ ] Add category creation form
- [ ] Implement logic for categories and subcategories
- [ ] Display categories in a grid
- [ ] Make categories clickable
