### ISSUE TITLE
User Story #6: Delete Categories

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#6]
EPIC: **Stock Items**

As a **site user**, I want to **delete categories**, so that I can **remove unnecessary categories**.

**Acceptance Criteria:**
1. Categories can be deleted.
2. Associated subcategories and stock items are deleted when deleting a category.

**Tasks:**
- [ ] Implement deletion functionality for categories
- [ ] Add confirmation before deletion
- [ ] Delete associated subcategories and stock items
