### ISSUE TITLE
User Story #9: Delete Stock Items

### ISSUE THREAD

**Issue by Julia-Wagner** [Julia-Wagner/PipeTracker#9]
EPIC: **Stock Items**

As a **site user**, I want to **delete stock items**, so that I can **remove items from my inventory**.

**Acceptance Criteria:**
1. Stock Items can be deleted.
2. Deleted items are removed from open delivery notes.

**Tasks:**
- [x] Implement deletion functionality for stock items
- [x] Add confirmation before deletion
- [x] Delete item from open delivery note
